# Generated by Django 5.2.8 on 2025-12-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_restaurant_description_restaurant_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/'),
        ),
    ]
